## Numpy Giriş

In [1]:
import numpy as np


## Numpy Arrays


In [2]:
denemeListe = [10 ,20, 30]

In [4]:
type(denemeListe)

list

In [5]:
np.array(denemeListe) 
# bir listeden np array türetilebilir

array([10, 20, 30])

In [6]:
matris = [[1,2,3], [4,5,6], [7,8,9]]

In [8]:
np.array(matris)
# bu şekilde de bir liste içinde listeden numpy matris oluşturulabilir

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## arange methodu

In [9]:
range(0,10)
list(range(12,24)) # range ile bir liste oluşturmak mümkündü

[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]

In [11]:
np.arange(10, 100,10) # numpy ile dizi oluşturulabilir


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

## zeros  

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
# Eğer matris oluşturmak istenilirse
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## linspace

In [19]:
np.linspace(2,20,3) 
# 2 VE 20 ARASINDA 3 tane sayı yazdırır

array([ 2., 11., 20.])

## eye

In [21]:
np.eye(10)
# birim, identity matris

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])