## Numpy-RANDOM

In [1]:
import numpy as np

In [7]:
np.random.randn(5)
# Normal dağılımlı array

array([ 0.4052983 ,  0.08276907,  1.98105339,  0.5372113 , -0.94938985])

In [9]:
np.random.randn(4,7)
# bu şekilde de bir matris oluşturulabilir

array([[ 0.68856642, -0.4174108 ,  1.25837701, -0.91641994,  0.60801419,
         2.6472685 ,  0.47045785],
       [-1.2550087 ,  1.18138885,  1.12760201, -0.35098039,  1.59705811,
        -0.90305842,  0.82215225],
       [ 0.91215124,  0.2719037 ,  0.47767814,  0.00907543, -0.92068918,
        -1.57501879,  0.58721765],
       [ 0.1412469 , -0.2492786 , -0.53920547, -1.02241866,  0.3087726 ,
        -0.12116031,  0.17862673]])

In [25]:
np.random.randint(0,10)
# randint metodu ile birlikte de random integerlar döndürür
# son yazılan sayı exclusive!

1

In [29]:
numpyDizi = np.random.randint(10,51,6)
# 6 elemandan oluşan bir dizi döndürür

In [28]:
numpyDizi

array([14, 11, 10, 10, 12, 21])