## Numpy Dizi Methodları

In [26]:
import numpy as np
benimDizim = np.arange(0,30)

In [27]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [28]:
# ortalama değer
benimDizim.mean()



14.5

In [30]:
# kümülatif toplamı verir
benimDizim.cumsum()

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325,
       351, 378, 406, 435], dtype=int32)

In [31]:
# Tüm diziyi verilen sayıyla doldurur
benimDizim.fill(10)

In [32]:
benimDizim

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [38]:
yeniDizi = np.arange(0,30)
yeniDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [42]:
# Diziyi 6x5 şeklinde reshape eder
yeniMatris = yeniDizi.reshape(6,5)
yeniMatris

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [44]:
# Matrisin transpozunu alır
yeniMatris.T

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [45]:
integerDizi = np.random.randint(0,100,24)

In [46]:
integerDizi

array([45, 93, 76, 55, 29,  2, 56, 98, 50, 27, 59, 48, 99, 46, 58, 88, 89,
       14, 33, 53, 18, 89, 46,  3])

In [48]:
# argmax ile max sayının indeksini görmek mümkündür
integerDizi.argmax()

12

In [50]:
integerDizi.max()

99

In [51]:
integerDizi.argmin()

5

In [53]:
integerDizi[5]

2