## Numpy-İndeksler

In [2]:
import numpy as np

In [5]:
ilkDizi = np.arange(0,30)

In [6]:
ilkDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
# 4 ve 12 indeksleri arasındaki veriyi yazdırdı, 12 hariç
ilkDizi[4:12]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
# diziye eleman eklenebilir
ilkDizi[25: 34] = -13

In [16]:
ilkDizi

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24, -13,
       -13, -13, -13, -13])

## Slicing ile indeks işlemi


In [19]:
arrayNew = np.arange(0,24)

In [20]:
arrayNew

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
# bu işleme slicing denir, hatırla
slicingArray = arrayNew[4: 14]

In [22]:
slicingArray

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [23]:
slicingArray[:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [24]:
slicingArray[:] = 400 

In [26]:
# slicingArray içerisindeki tüm elemanlar 400 oldu
slicingArray

array([400, 400, 400, 400, 400, 400, 400, 400, 400, 400])

In [27]:
# slicingArray, arrayNew e ait bir parça gibi davranır
arrayNew

array([  0,   1,   2,   3, 400, 400, 400, 400, 400, 400, 400, 400, 400,
       400,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [28]:
# Burada da elemanların değiştini görmekteyiz

In [31]:
# Bu işlem olmasın istersek kopyasını alabiliriz
arrayNew = np.arange(0,24)
arrayCopy = arrayNew.copy()

In [32]:
arrayCopy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [33]:
slicingCopy = arrayCopy[4: 19]

In [34]:
slicingCopy

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [35]:
slicingCopy[:] = 400

In [36]:
slicingCopy

array([400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400,
       400, 400])

In [37]:
# Herhangi bir değişiklik olmaz
arrayNew

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [38]:
# Kopya dizi değişir
arrayCopy

array([  0,   1,   2,   3, 400, 400, 400, 400, 400, 400, 400, 400, 400,
       400, 400, 400, 400, 400, 400,  19,  20,  21,  22,  23])