## Matrix indexleri

In [13]:
import numpy as np

In [16]:
matrisİndex = np.array([[10,20, 30], [12, 24,36], [16,32,48]])

In [17]:
matrisİndex

array([[10, 20, 30],
       [12, 24, 36],
       [16, 32, 48]])

In [19]:
matrisİndex.shape

(3, 3)

In [30]:
# Ya da liste ile de matris oluşturulabilir
listeDeneme = [[1,2,3], [10,20,30], [33,63,93]]

In [31]:
listeDeneme

[[1, 2, 3], [10, 20, 30], [33, 63, 93]]

In [33]:
# Yine numpy kullanarak matris oluşturuldu
matrixDeneme = np.array(listeDeneme)
matrixDeneme

array([[ 1,  2,  3],
       [10, 20, 30],
       [33, 63, 93]])

In [34]:
matrixDeneme[2][1]

63

In [38]:
# Bu iki işlem de birbirinin aynısıdr
matrixDeneme[2,1]

array([ 2, 20, 63])

In [39]:
# Tek bir satır ya da sütun alınmak istenirse
matrixDeneme[:,2]

array([ 3, 30, 93])

## Fancy İndexing


In [41]:
listem = [[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20]]

In [42]:
yeniMatrix = np.array(listem)

In [43]:
yeniMatrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [45]:
#fancy indexing
yeniMatrix[[0,1,3]]
# 0,1 ve 3. satırları verir

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [46]:
slicingMatrix = yeniMatrix[[0,1,3]]

In [47]:
slicingMatrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])