## Numpy-Toplama-Çıkarma-Büyüktür-Küçüktür

In [3]:
import numpy as np

In [10]:
yeniDizi = np.random.randint(1,100,20)

In [11]:
yeniDizi

array([79, 13, 53, 58, 92, 31, 86, 72, 54, 98, 14, 20, 74, 18, 78, 46,  1,
       47, 21, 32])

In [12]:
sonuc = yeniDizi > 24

In [13]:
sonuc

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True, False,  True,  True, False,  True,
       False,  True])

## Önemli

In [15]:
# 24'ten büyük sayıları oluşturduğumuz sonuc dizisini içeri koyarak bulabiliriz
yeniDizi[sonuc]

array([79, 53, 58, 92, 31, 86, 72, 54, 98, 74, 78, 46, 47, 32])

In [16]:
# ya da
yeniDizi[yeniDizi>24]

array([79, 53, 58, 92, 31, 86, 72, 54, 98, 74, 78, 46, 47, 32])

## Toplama-çıkarma- çarpma-bölme

In [17]:
sonDizi = np.arange(5,25)

sonDizi

In [19]:
toplam = sonDizi + sonDizi 

In [20]:
toplam 

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [21]:
sonDizi* sonDizi

array([ 25,  36,  49,  64,  81, 100, 121, 144, 169, 196, 225, 256, 289,
       324, 361, 400, 441, 484, 529, 576])

In [22]:
sonDizi-sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
sonDizi/ sonDizi

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

## Karekök alma


In [24]:
np.sqrt(sonDizi)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [27]:
diziNew = np.arange(4,128,4**2)

In [28]:
diziNew

array([  4,  20,  36,  52,  68,  84, 100, 116])

In [29]:
np.sqrt(diziNew)

array([ 2.        ,  4.47213595,  6.        ,  7.21110255,  8.24621125,
        9.16515139, 10.        , 10.77032961])

In [30]:
np.max(diziNew)

116

In [31]:
np.min(diziNew)

4